main:
	g++ 1043335.cpp ScalableVectorGraphicsGenerator.cpp ScalableVectorGraphicsGenerator.hpp -o a.out

run :
	./a.out design_00.isc design_00

clean:
	rm a.out

all: clean main run

start: main run


